name: mylist

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: dep install
        run: |
          yarn install --immutable

      - name: run
        run: |
          yarn run filter
          yarn run trackerslist_all
          yarn run trackerslist_best

      - name: format
        run: |
          sed -i '/^!/d;/^\s*$/d' trackerslist_all.txt
          sed -i '/^!/d;/^\s*$/d' trackerslist_best.txt
          sed -i '/^\s*$/d' filter.txt

      - name: commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git add -u
          git commit -m "update"
          git push origin main
